/** Shared IPC channel constants. Runtime-neutral: no Electron imports. */

export const IPC_INVOKE_CHANNELS = [
  "bugs:add-attachment",
  "bugs:capture-context",
  "bugs:create",
  "bugs:delete",
  "bugs:get",
  "bugs:get-context-snapshot",
  "bugs:list",
  "bugs:list-attachments",
  "bugs:pick-attachment-file",
  "bugs:remove-attachment",
  "bugs:update",
  "chains:create",
  "chains:delete",
  "chains:list",
  "chains:run",
  "chains:update",
  "commands:add",
  "commands:detect-variables",
  "commands:get",
  "commands:get-directories",
  "commands:remove",
  "commands:run",
  "commands:run-adhoc",
  "commands:stop",
  "commands:toggle-pin",
  "commands:update",
  "config:export",
  "config:export-to-file",
  "config:import",
  "config:import-preview",
  "containers:get",
  "containers:logs",
  "containers:pause",
  "containers:remove",
  "containers:restart",
  "containers:start",
  "containers:stop",
  "containers:unpause",
  "dialog:open-folder",
  "docker:list",
  "docker:logs:subscribe",
  "docker:logs:unsubscribe",
  "docker:start",
  "docker:stop",
  "engine:clear",
  "engine:clear-search-session",
  "engine:git-insights",
  "engine:index",
  "engine:is-available",
  "engine:search",
  "engine:state",
  "engine:stats",
  "files:clearIndex",
  "files:list",
  "files:openInEditor",
  "files:revealInFolder",
  "files:search",
  "git:commit",
  "git:create-pr",
  "git:diff",
  "git:get-state",
  "git:push",
  "health:get-latest",
  "health:get-run",
  "health:list-runs",
  "health:run",
  "history:clear",
  "history:get",
  "history:listRecent",
  "history:output",
  "history:remove",
  "llm:bundle-context",
  "notes:get",
  "notes:update",
  "preferences:get",
  "preferences:update",
  "project:inspect",
  "projects:add",
  "projects:get",
  "projects:open-editor",
  "projects:open-folder",
  "projects:open-terminal",
  "projects:remove",
  "projects:restart-dev-stack",
  "projects:set-linked-containers",
  "projects:start-dev-stack",
  "projects:stop-dev-stack",
  "projects:toggle-pin",
  "projects:update",
  "shell:open-external",
  "terminal:close",
  "terminal:create",
  "terminal:resize",
  "terminal:write",
  "triggers:create",
  "triggers:delete",
  "triggers:emit",
  "triggers:list",
  "triggers:pending-confirmations",
  "triggers:respond-confirmation",
  "triggers:update",
  "wsl:list-distros"
] as const

export type IpcInvokeChannel = (typeof IPC_INVOKE_CHANNELS)[number]

export const IPC_EVENT_CHANNELS = [
  "chains:progress",
  "docker:logs:data",
  "docker:logs:end",
  "docker:logs:error",
  "engine:indexing-completed",
  "engine:indexing-started",
  "runs:output",
  "runs:started",
  "runs:status",
  "terminal:data",
  "terminal:error",
  "terminal:exit",
  "tray:terminal-created",
  "triggers:confirmation-requested"
] as const

export type IpcEventChannel = (typeof IPC_EVENT_CHANNELS)[number]

export const IpcChannels = {
  "BugsAddAttachment": "bugs:add-attachment" as IpcInvokeChannel,
  "BugsCaptureContext": "bugs:capture-context" as IpcInvokeChannel,
  "BugsCreate": "bugs:create" as IpcInvokeChannel,
  "BugsDelete": "bugs:delete" as IpcInvokeChannel,
  "BugsGet": "bugs:get" as IpcInvokeChannel,
  "BugsGetContextSnapshot": "bugs:get-context-snapshot" as IpcInvokeChannel,
  "BugsList": "bugs:list" as IpcInvokeChannel,
  "BugsListAttachments": "bugs:list-attachments" as IpcInvokeChannel,
  "BugsPickAttachmentFile": "bugs:pick-attachment-file" as IpcInvokeChannel,
  "BugsRemoveAttachment": "bugs:remove-attachment" as IpcInvokeChannel,
  "BugsUpdate": "bugs:update" as IpcInvokeChannel,
  "ChainsCreate": "chains:create" as IpcInvokeChannel,
  "ChainsDelete": "chains:delete" as IpcInvokeChannel,
  "ChainsList": "chains:list" as IpcInvokeChannel,
  "ChainsRun": "chains:run" as IpcInvokeChannel,
  "ChainsUpdate": "chains:update" as IpcInvokeChannel,
  "CommandsAdd": "commands:add" as IpcInvokeChannel,
  "CommandsDetectVariables": "commands:detect-variables" as IpcInvokeChannel,
  "CommandsGet": "commands:get" as IpcInvokeChannel,
  "CommandsGetDirectories": "commands:get-directories" as IpcInvokeChannel,
  "CommandsRemove": "commands:remove" as IpcInvokeChannel,
  "CommandsRun": "commands:run" as IpcInvokeChannel,
  "CommandsRunAdhoc": "commands:run-adhoc" as IpcInvokeChannel,
  "CommandsStop": "commands:stop" as IpcInvokeChannel,
  "CommandsTogglePin": "commands:toggle-pin" as IpcInvokeChannel,
  "CommandsUpdate": "commands:update" as IpcInvokeChannel,
  "ConfigExport": "config:export" as IpcInvokeChannel,
  "ConfigExportToFile": "config:export-to-file" as IpcInvokeChannel,
  "ConfigImport": "config:import" as IpcInvokeChannel,
  "ConfigImportPreview": "config:import-preview" as IpcInvokeChannel,
  "ContainersGet": "containers:get" as IpcInvokeChannel,
  "ContainersLogs": "containers:logs" as IpcInvokeChannel,
  "ContainersPause": "containers:pause" as IpcInvokeChannel,
  "ContainersRemove": "containers:remove" as IpcInvokeChannel,
  "ContainersRestart": "containers:restart" as IpcInvokeChannel,
  "ContainersStart": "containers:start" as IpcInvokeChannel,
  "ContainersStop": "containers:stop" as IpcInvokeChannel,
  "ContainersUnpause": "containers:unpause" as IpcInvokeChannel,
  "DialogOpenFolder": "dialog:open-folder" as IpcInvokeChannel,
  "DockerList": "docker:list" as IpcInvokeChannel,
  "DockerLogsSubscribe": "docker:logs:subscribe" as IpcInvokeChannel,
  "DockerLogsUnsubscribe": "docker:logs:unsubscribe" as IpcInvokeChannel,
  "DockerStart": "docker:start" as IpcInvokeChannel,
  "DockerStop": "docker:stop" as IpcInvokeChannel,
  "EngineClear": "engine:clear" as IpcInvokeChannel,
  "EngineClearSearchSession": "engine:clear-search-session" as IpcInvokeChannel,
  "EngineGitInsights": "engine:git-insights" as IpcInvokeChannel,
  "EngineIndex": "engine:index" as IpcInvokeChannel,
  "EngineIsAvailable": "engine:is-available" as IpcInvokeChannel,
  "EngineSearch": "engine:search" as IpcInvokeChannel,
  "EngineState": "engine:state" as IpcInvokeChannel,
  "EngineStats": "engine:stats" as IpcInvokeChannel,
  "FilesClearIndex": "files:clearIndex" as IpcInvokeChannel,
  "FilesList": "files:list" as IpcInvokeChannel,
  "FilesOpenInEditor": "files:openInEditor" as IpcInvokeChannel,
  "FilesRevealInFolder": "files:revealInFolder" as IpcInvokeChannel,
  "FilesSearch": "files:search" as IpcInvokeChannel,
  "GitCommit": "git:commit" as IpcInvokeChannel,
  "GitCreatePr": "git:create-pr" as IpcInvokeChannel,
  "GitDiff": "git:diff" as IpcInvokeChannel,
  "GitGetState": "git:get-state" as IpcInvokeChannel,
  "GitPush": "git:push" as IpcInvokeChannel,
  "HealthGetLatest": "health:get-latest" as IpcInvokeChannel,
  "HealthGetRun": "health:get-run" as IpcInvokeChannel,
  "HealthListRuns": "health:list-runs" as IpcInvokeChannel,
  "HealthRun": "health:run" as IpcInvokeChannel,
  "HistoryClear": "history:clear" as IpcInvokeChannel,
  "HistoryGet": "history:get" as IpcInvokeChannel,
  "HistoryListRecent": "history:listRecent" as IpcInvokeChannel,
  "HistoryOutput": "history:output" as IpcInvokeChannel,
  "HistoryRemove": "history:remove" as IpcInvokeChannel,
  "LlmBundleContext": "llm:bundle-context" as IpcInvokeChannel,
  "NotesGet": "notes:get" as IpcInvokeChannel,
  "NotesUpdate": "notes:update" as IpcInvokeChannel,
  "PreferencesGet": "preferences:get" as IpcInvokeChannel,
  "PreferencesUpdate": "preferences:update" as IpcInvokeChannel,
  "ProjectInspect": "project:inspect" as IpcInvokeChannel,
  "ProjectsAdd": "projects:add" as IpcInvokeChannel,
  "ProjectsGet": "projects:get" as IpcInvokeChannel,
  "ProjectsOpenEditor": "projects:open-editor" as IpcInvokeChannel,
  "ProjectsOpenFolder": "projects:open-folder" as IpcInvokeChannel,
  "ProjectsOpenTerminal": "projects:open-terminal" as IpcInvokeChannel,
  "ProjectsRemove": "projects:remove" as IpcInvokeChannel,
  "ProjectsRestartDevStack": "projects:restart-dev-stack" as IpcInvokeChannel,
  "ProjectsSetLinkedContainers": "projects:set-linked-containers" as IpcInvokeChannel,
  "ProjectsStartDevStack": "projects:start-dev-stack" as IpcInvokeChannel,
  "ProjectsStopDevStack": "projects:stop-dev-stack" as IpcInvokeChannel,
  "ProjectsTogglePin": "projects:toggle-pin" as IpcInvokeChannel,
  "ProjectsUpdate": "projects:update" as IpcInvokeChannel,
  "ShellOpenExternal": "shell:open-external" as IpcInvokeChannel,
  "TerminalClose": "terminal:close" as IpcInvokeChannel,
  "TerminalCreate": "terminal:create" as IpcInvokeChannel,
  "TerminalResize": "terminal:resize" as IpcInvokeChannel,
  "TerminalWrite": "terminal:write" as IpcInvokeChannel,
  "TriggersCreate": "triggers:create" as IpcInvokeChannel,
  "TriggersDelete": "triggers:delete" as IpcInvokeChannel,
  "TriggersEmit": "triggers:emit" as IpcInvokeChannel,
  "TriggersList": "triggers:list" as IpcInvokeChannel,
  "TriggersPendingConfirmations": "triggers:pending-confirmations" as IpcInvokeChannel,
  "TriggersRespondConfirmation": "triggers:respond-confirmation" as IpcInvokeChannel,
  "TriggersUpdate": "triggers:update" as IpcInvokeChannel,
  "WslListDistros": "wsl:list-distros" as IpcInvokeChannel,
  "OnChainsProgress": "chains:progress" as IpcEventChannel,
  "OnDockerLogsData": "docker:logs:data" as IpcEventChannel,
  "OnDockerLogsEnd": "docker:logs:end" as IpcEventChannel,
  "OnDockerLogsError": "docker:logs:error" as IpcEventChannel,
  "OnEngineIndexingCompleted": "engine:indexing-completed" as IpcEventChannel,
  "OnEngineIndexingStarted": "engine:indexing-started" as IpcEventChannel,
  "OnRunsOutput": "runs:output" as IpcEventChannel,
  "OnRunsStarted": "runs:started" as IpcEventChannel,
  "OnRunsStatus": "runs:status" as IpcEventChannel,
  "OnTerminalData": "terminal:data" as IpcEventChannel,
  "OnTerminalError": "terminal:error" as IpcEventChannel,
  "OnTerminalExit": "terminal:exit" as IpcEventChannel,
  "OnTrayTerminalCreated": "tray:terminal-created" as IpcEventChannel,
  "OnTriggersConfirmationRequested": "triggers:confirmation-requested" as IpcEventChannel,
} as const

export const SAFE_EXTERNAL_URL_SCHEMES = ['https:', 'http:'] as const

export function isSafeExternalUrl(raw: string): boolean {
  const trimmed = raw.trim()
  if (!trimmed) return false
  try {
    const parsed = new URL(trimmed)
    if (!(SAFE_EXTERNAL_URL_SCHEMES as readonly string[]).includes(parsed.protocol)) {
      return false
    }
    if (
      parsed.protocol === 'http:' &&
      parsed.hostname !== 'localhost' &&
      parsed.hostname !== '127.0.0.1' &&
      parsed.hostname !== '[::1]'
    ) {
      return false
    }
    return true
  } catch {
    return false
  }
}

